Spring Unit Test
Seydalievnikolay/springBoot pull request #6
Opened 2023-07-21 13:27 UTC by Seydalievnikolay

2023-07-24 11:41 UTC, isavinov approved these changes

2023-07-27 13:30 UTC, isavinov requested changes

2023-07-27 13:30 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        List<EmployeeDTO> excepted = List.of(EmployeeDTO.fromEmployee(employee), EmployeeDTO.fromEmployee(employee2));
Mapper это тоже мок, его поведение нужно сконфигурировать. Без этого он не понимает, как из entity сделать dto

2023-07-27 13:30 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        EmployeeDTO actual = out.updateEmployeeById(1, employee);
Mapper это тоже мок, его поведение нужно сконфигурировать. Без этого он не понимает, как из entity сделать dto

2023-07-28 13:15 UTC, isavinov requested changes

2023-07-28 13:15 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        when(repositoryMock.findAll()).thenReturn(employeeEntities);
Мокать нужно тот метод, который вызывается внутри тестируемого метода
`when(repositoryMock.findAllEmployeeFullInfo()).thenReturn(...)`

2023-07-28 13:15 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        List<EmployeeFullInfo> employeeList = out.getEmployeesBySalaryGreaterThan(lowerBorder);
сначала мокаем, потом вызываем тестируемый метод

```
when(repositoryMock.findAllEmployeeFullInfo()).thenReturn(employeeList);
List<EmployeeFullInfo> employeeList = out.getEmployeesBySalaryGreaterThan(lowerBorder);
```

2023-07-28 13:15 UTC, isavinov commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        when(repositoryMock.findById(1)).thenReturn(Optional.of(employee));
Это лишняя строка. метод repositoryMock.findById(1) внутри метода out.deleteById(2) не вызывается. Удали эту строку и тест будет проходить

2023-07-28 15:14 UTC, Seydalievnikolay commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        List<EmployeeFullInfo> employeeList = out.getEmployeesBySalaryGreaterThan(lowerBorder);
org.opentest4j.AssertionFailedError: 
Expected :[EmployeeFullInfo{name='Sergey', salary=1000.0, positionName='VideoMaker'}]
Actual   :[EmployeeFullInfo{name='Ivan', salary=200000.0, positionName='Dev'}]

2023-07-28 15:15 UTC, Seydalievnikolay commented on src/test/java/ru/skypro/lessons/springboot/EmployeeApplication/service/EmployeeServiceTest.java
> +        List<EmployeeFullInfo> employeeList = out.getEmployeesBySalaryGreaterThan(lowerBorder);
Ничего не изменилось, может метод неправильно написан в репозитории?
Остальные исправил, спасибо

2023-08-01 09:37 UTC, merged